name: Deploy Ansible Playbook

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Run playbook on control server
        run: |
          ssh -o StrictHostKeyChecking=no \
          -i ~/.ssh/id_rsa \
          ec2-user@98.86.146.34 \
          "git config --global --add safe.directory /home/ec2-user/ansible-projects && \
           cd /home/ec2-user/ansible-projects && \
           ansible-playbook -i inventory ansiblescript.yml"
